apiVersion: batch/v1
kind: Job
metadata:
  name: load-test
spec:
  parallelism: 5         # 5 pods running at the same time
  completions: 5         # total 5 pods must finish
  backoffLimit: 2        # retries if a pod fails
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: load
        image: busybox
        command:
        - sh
        - -c
        - |
          i=0
          while [ $i -lt 120 ]; do
            wget -q -O- http://online-shop-preview.default.svc.cluster.10.244.0.57:3000/
            i=$((i+1))
          done
